### ISSUE TITLE
Loot does not appear in the inventory

### ISSUE THREAD

**Issue by ziceptor** [trentech/WalletDrop#3]
Loot drops , but the inventory does not appear.

forge-1.10.2-12.18.2.2098-universal.jar
spongeforge-1.10.2-2098-5.1.0-BETA-1814.jar
walletdrop-5.1.0-0.1.1.jar

**Comment by ziceptor** [comment]
[23:23:52] [Server thread/ERROR] [walletdrop]: Cannot get AgeableData
[23:23:55] [Server thread/ERROR] [walletdrop]: Cannot get AgeableData
[23:23:57] [Server thread/ERROR] [walletdrop]: Cannot get AgeableData

**Comment by trentech** [comment]
It's not suppose to. The item is virtual. Once picked up its converted to money that's deposited to players account.

Also that error can be ignored. As your other issue this is a Sponge Implementation issue and will go away once the Sponge team implements AgeableData
