### ISSUE TITLE
[STDERR]: [org.spongepowered.common.data.util.DataUtil:deserializeManipulatorList

### ISSUE THREAD

**Issue by ziceptor** [trentech/WalletDrop#4]
@trentech 
Continuous spam in the console after you delete the plugin. 

http://pastebin.com/8fpg4Wq1

forge-1.10.2-12.18.2.2123-universal.jar
spongeforge-1.10.2-2123-5.1.0-BETA-1888.jar
walletdrop-5.1.0-0.1.1.jar

**Comment by trentech** [comment]
This is because this plugin adds custom data to entities. Without the plugin the server cannot interpret the data. The error is unavoidable but it's also harmless and will go away on it's own over time.

**Comment by ziceptor** [comment]
Thank you!
