### ISSUE TITLE
[Server thread/ERROR] [Sponge]: The Scheduler tried to run the task walletdrop-S-9 owned by Plugin{

### ISSUE THREAD

**Issue by ziceptor** [trentech/WalletDrop#5]
forge-1.11-13.19.0.2168-universal.jar
spongeforge-1.11-2168-6.0.0-BETA-1924.jar
walletdrop-5.1.0-0.2.0.jar

After killing the console shows an error. Cash is credited.

http://pastebin.com/d2C3NuEW

**Comment by ziceptor** [comment]
But the inventory remains the gold. It can be thrown out and not pick up a limited number of times. Balance increases.

**Comment by trentech** [comment]
This still an issue with latest version?

**Comment by ziceptor** [comment]
Yes.
```
forge-1.11-13.19.0.2178-universal.jar
spongeforge-1.11-2178-6.0.0-BETA-1962.jar
walletdrop-5.1.0-0.2.1.jar
```
http://pastebin.com/unCAcxHV

**Comment by ziceptor** [comment]
Works!

forge-1.11-13.19.0.2178-universal.jar
spongeforge-1.11-2178-6.0.0-BETA-1981.jar
walletdrop-5.1.0-0.2.1.jar

**Comment by Adnan1234** [comment]
Is this issue now fixed ?

**Comment by ziceptor** [comment]
Works for me.

**Comment by Adnan1234** [comment]
With latest version of Sponge. It works. 

SpongeVanilla: 1.11-6.0.0-BETA-184
