### ISSUE TITLE
Error in console after removal

### ISSUE THREAD

**Issue by Adnan1234** [trentech/WalletDrop#6]
I was going to use this plugin, however couldn't disable the physical item drop. After removal of this plugin, it still spams console with an error. I've got no idea on how to get rid of these errors.

https://paste.ubuntu.com/23608271/

Minecraft: 1.11
SpongeAPI: 6.0.0-SNAPSHOT-af15769
SpongeVanilla: 1.11-6.0.0-BETA-183
I used the latest version that is available for download for WalleteDrop.

Any help will be appreciated.

**Comment by ziceptor** [comment]
@Adnan1234 Read this:
https://github.com/trentech/WalletDrop/issues/4
and
https://github.com/trentech/WalletDrop/issues/5

**Comment by Adnan1234** [comment]
Thanks

**Comment by trentech** [comment]
I've added something in the next coming update to help with this. There will be an entry in the default config called "uninstall". Set this to true and restart the server, DO NOT remove the plugin yet. On start the plugin will not function, but a listener will register that will monitor entities and remove any WalletDrop data as it's found. Let this run for a couple days and this should prevent any errors after the plugin is removed.
