### ISSUE TITLE
Ageable Data

### ISSUE THREAD

**Issue by connorhartley** [trentech/WalletDrop#7]
This seems to occur a lot...

`[walletdrop]: Cannot get AgeableData`

Is there a way to fix this or prevent it from being spammed a lot in console?

**Comment by aso824** [comment]
I turned off some mobs (frequency=0). I see that this error occurs only when I killed mob which don't give money.

**Comment by trentech** [comment]
This error should only occur on Zombies and it's an implementation issue. I'll remove it from the console

**Comment by connorhartley** [comment]
Alright. Thanks.

**Comment by zerafox** [comment]
I have this appearing in console whether or not I've killed something. o.O

**Comment by trentech** [comment]
Fixed
