### ISSUE TITLE
Update to API 6

### ISSUE THREAD

**Issue by yololetsplay** [trentech/WalletDrop#8]
Hey there ;]

Dropping money from monsters and from players, both not work :/

Using newest sponge API 6 version spongeforge-1.11.2-2201-6.0.0-BETA-2046.
Do you have any idea I can fix this? :/
I really really love ur plugin!

Greetz,
Hannes

**Comment by trentech** [comment]
Partially fixed but the fix added a new bug I have to fix

**Comment by yololetsplay** [comment]
Alright.

**Comment by EvilCh33z** [comment]
any ETA on API6 update?

**Comment by trentech** [comment]
https://trentech.org/jenkins/job/Wallet%20Drop/
