### ISSUE TITLE
 Could not pass SpawnEntityEvent$ChunkLoad$Impl to Plugin{id=walletdrop...

### ISSUE THREAD

**Issue by ziceptor** [trentech/WalletDrop#9]
1.11.2-2227-6.0.0-BETA-2249 (2251) <-- Spam in console
1.11.2-2227-6.0.0-BETA-2244 <-- Works
forge-1.11.2-13.20.0.2227-universal.jar

simon816: There was a recent change to the 'bleeding' API snapshots.

https://gist.github.com/ziceptor/03e116e590d1b74b336ceb8ead4e47f7

**Comment by ziceptor** [comment]
Rare. https://pastebin.com/WmdKuUhB

**Comment by trentech** [comment]
The event fires on an empty array? That's dumb. Ok I'll fix it this weekend. Idk why they removed the ability to get the targeted world to begin with. Also dumb. Sorry, just annoyed

**Comment by ziceptor** [comment]
I don't understand why. I thought that because of the hordes of zombies, but it happens with no mobs.

**Comment by ziceptor** [comment]
I think the changes made because of the contexts. But I could be wrong.

**Comment by trentech** [comment]
Well I just discovered I can edit files directly from github so I just added a change that should solve the issue. Can you test and report back?

**Comment by ziceptor** [comment]
ok

**Comment by ziceptor** [comment]
Crash Report  https://gist.github.com/ziceptor/bae49f53347e61de0707e9c7e7dda1e4

**Comment by ziceptor** [comment]
Any news?

**Comment by trentech** [comment]
Oh I thought I had already replied to this. My bad

Haven't released anything changed for api 6 but I've been transitioning my plugins to a new structure so they now require the ProjectCore Library as a dependency. I assumed you had figured that out already considering the last update you ran just fine which also required it

**Comment by trentech** [comment]
https://github.com/trentech/ProjectCore

**Comment by ziceptor** [comment]
Works. Thank you!
